### ISSUE TITLE
Screen Size takes into account menu bar

### ISSUE THREAD

**Issue by eipark** [jigish/slate#24]
It seems that screen size takes into account the OS X menu bar making things like stacking two windows on top of each other not line up properly. Can there be a built in property where the screenSizeY is the height of the available window region excluding the menu bar? Thanks Jigish!

**Comment by jigish** [comment]
Hey man! sorry it took so long to comment on this. Do you mean screenSizeYTotal or something that is not just the visible area but the area behind the menu bar as well? And what problems do you have stacking windows? That should work just fine...

**Comment by pstadler** [comment]
The problem is, that `Y` doesn't take the menubar into account. For example if `Y=30` the window is placed 8px below the menubar.

I'm using `alias menubarHeight 22` to work around this issue.

**Comment by jigish** [comment]
Interesting. Can you send me a description of how your monitors are placed, where your dock is, which monitor your menu bar is on, etc? I've seen this issue before, but thought I fixed it. Maybe it is a configuration I haven't thought of or seen before. Also, OS version and Slate version would be nice as well.

Thanks!

**Comment by jigish** [comment]
@eipark or @pstadler is this still an issue? If so OS version, Slate version and .slate file would be greatly appreciated.

**Comment by paddykontschak** [comment]
I can confirm that this is still an issue. I had to add a special alias for the menubar just like @pstadler did.

Slate 1.0.5
Mac OS X 10.8.2
[.slate](https://github.com/paddykontschak/dotfiles/blob/master/home/.slate#L21)

**Comment by pstadler** [comment]
My [.slate](https://github.com/pstadler/dotfiles/blob/master/slate) for reference.

**Comment by jigish** [comment]
One thing I've noticed is that neither of you are using `screenOriginX` and `screenOriginY`. Those will be the proper origin under the menu bar which you can then add to. Maybe that will help?

**Comment by pstadler** [comment]
Ok, I was able to get rid of my custom variable by using `screenOriginY` ([commit diff](https://github.com/pstadler/dotfiles/commit/37239ea156190fdcd0b1603dab041e030f2aae36)).

However, it doesn't really solve the problem as the coordinates for placing windows should start from `0/screenOriginY` and not from `0/0`.

Example: `move 10;10 ...` should internally be translated to `10;32`

Thanks again for this awesome tool! :-)

**Comment by jigish** [comment]
The issue is when you have multiple monitors, `0,0` refers to the main monitor's `0,0`. In order to get to the second monitor you _need_ `screenOriginX` and `screenOriginY` which is why it should be there for most move operations. I explicitly do _not_ want to auto-append `screenOriginY` to coordinates because it doesn't always make sense. `screenOriginX` and `screenOriginY` are meant to be the "this is the screen's origin" coordinates.

**Comment by jigish** [comment]
What problem are you trying to solve exactly? I feel like there should be a way to do so with the current implementation.

**Comment by pstadler** [comment]
To place a window you say what distance it should have from the top-left pixel. Right now this top-left pixel is above the menubar, and not below it (as it should be, because you can't place windows on the menubar).

That's why I have to calculate the position of the windows by adding 22px (= menubar height) to the Y-coordinate manually.
screenOriginY seems to know about the menubar, its value is 22px.

It doesn't matter much to me, you can close this if you want.
